### ISSUE TITLE
Org mode code blocks remain variable pitch with org-src-fontify-natively enabled

### ISSUE THREAD

**Issue by anpandey** [jabranham/mixed-pitch#2] opened 2017-12-03 05:52 UTC
Within Org mode, if  `org-src-fontify` is set to `t` and a code block specifies any language at all (even those not in `org-src-lang-modes`), the code block changes back to the variable pitch font. The only exception is when the syntax has a face defined in the major mode of the language. For example, if my block looks something like
```
#+BEGIN_SRC python
if foo()
#+END_SRC
```
then `if` is fixed pitch, since it has the face `font-lock-keyword-face`, but `foo()` is still variable pitch.

**Comment by jabranham** [comment] 2017-12-04 00:35
I can't reproduce this. For me, nothing in that python block gets variable pitch.

I've noticed that if I replace "python" with "emacs-lisp," then the pitch doesn't get set correctly, but then you're not dealing with correct code anyway.

I'll look more into it, but can you give me a recipe from "emacs -Q" that reproduces the issue?

Also please include emacs version and what OS you're using.

**Comment by anpandey** [comment] 2017-12-05 15:47
I was able to reproduce the bug on Emacs 25.1.1 on Ubuntu 17.04 with the MELPA version of mixed-pitch installed by the minimal setup of `emacs -Q --eval "(progn (require 'package) (package-initialize) (require 'mixed-pitch) (setq org-src-fontify-natively t))"`. After creating a new blank buffer, activating `org-mode` and `mixed-pitch-mode` and pasting the following valid python source code block into buffer:
```
#+BEGIN_SRC python
  if foo():
      do_something()
  else:
      do_something_else()
#+END_SRC
```
only the keywords `if` and `else` are fixed pitch, while all the function calls are variable pitch.

 I should also mention that I was able to resolve this by adding `'org-block-background` to `mixed-pitch-fixed-pitch-faces`, but I'm not sure what the implications of using an overlay face might be.

**Comment by jabranham** [comment] 2017-12-05 17:53
Thanks for the recipie. I can reproduce this on Emacs 25.3 and org-version 8.2.10 that comes with it.

However, I cannot reproduce it after updating org mode to the current version 9.1.3. It is likely due to this entry in the ORG-NEWS for org version 9.0:

```
*** The ~org-block~ face is inherited by ~src-blocks~

This works also when =org-src-fontify-natively= is non-nil.  It is also
possible to specify per-languages faces.  See =org-src-block-faces= and
the manual for details.
```

which at least suggests that there isn't a straightforward fix for this in org versions < 9.0.

I suggest updating org to at least 9.0, released in November 2016.

**Comment by anpandey** [comment] 2017-12-09 05:57
Thanks, upgrading to org version 9.1.4 resolved the issue. Would it still be appropriate to add  'org-block-background to `mixed-pitch-fixed-pitch-faces` to enable compatibility with older versions of org?

**Comment by jabranham** [comment] 2017-12-09 16:37
Great, glad to hear that solved it.

I'm hesitant to add something that's not a face to mixed-pitch-fixed-pitch-faces. I also suspect (but haven't verified) that adding org-block to mixed-pitch-fixed-pitch-faces will make all blocks that begin with #+BEGIN fixed-pitch, which may or may not be appropriate (e.g. LATEX blocks).

I'll add a note to the documentation that mixed-pitch-mode works best with org versions >= 9.0.

Thanks!

**Closed as completed** 2017-12-09 16:42 UTC
